### ISSUE TITLE
Release a new version v0.10.2 in foreman-packaging

### ISSUE THREAD

**Issue by sbernhard** [theforeman/foreman_fog_proxmox#140]
Hi,

can you please create a new rubygem release of foreman-fog-proxmox and also update the foreman-packaging to 0.10.2?

Thanks a lot.

Best regads,
Bernhard

**Comment by tristanrobert** [comment]
Hello,

- the gem is already published since february, 12th: https://rubygems.org/gems/foreman_fog_proxmox/versions/0.10.2

- the deb is already published: https://github.com/theforeman/foreman-packaging/pull/4708

- the rpm was stopped by another foreman package: https://github.com/theforeman/foreman-packaging/pull/4709. Now I can continue. I will do it today.

**Comment by tristanrobert** [comment]
rpm done: https://github.com/theforeman/foreman-packaging/pull/4992
