### ISSUE TITLE
Proxmox hosts are not deleted in bulk job

### ISSUE THREAD

**Issue by brimioulle** [theforeman/foreman_fog_proxmox#176]
When trying to delete proxmox hosts via bulk action the task returns "success" but hosts are not being deleted. Deleting of a single host by pushing the "Delete"-button in host view still works though.

Steps to Reproduce:
1. Go to "All Hosts"
2. Select a proxmox host
3. Go to "Select Action" and execute "Delete host"

Actual results:
The tasks returns "success" but the host is not deleted.

Expected results:
The host is deleted.

**Comment by tristanrobert** [comment]
This issue occurs since foreman  2.2-rc4 when they introduced Rails Observable Model in https://github.com/theforeman/foreman/commit/5d828bc6823c0da06d720b9f3e2905455826e6ae. Deletion does not call anymore vm destroy function. Plugin must now introduces subscribers to events as deletion, creation and update! It needs a big change to do in the plugin!

**Comment by tristanrobert** [comment]
You should add `:destroy_vm_on_host_delete: true` in `config/settings.yaml` of your foreman installation. It will delete vm associated to host on its deletion.
