### ISSUE TITLE
Plugin version 0.8 breaks GCE compute resource plugin

### ISSUE THREAD

**Issue by pdzionek** [theforeman/foreman_fog_proxmox#87]
**Describe the bug**
When a proxmox plugin is installed it messes up with GCE plugin and breaks it. This issue was described here: [Foreman Forum](https://community.theforeman.org/t/google-cloud-compute-ressource-header-field-value-cannot-include-cr-lf/12846/17) in last few posts

Quote from the last post by @tbrisker:
> I’m afraid this would need to be fixed in the plugin, i think at https://github.com/theforeman/foreman_fog_proxmox/blob/master/app/views/compute_resources_vms/form/proxmox/_add_vm_type_to_volumes_edit.html.erb#L18. The plugin seems to assume that all compute resources have a type method, which apparently isn’t the case for GCE. There may be other assumptions done inside the plugin that will need to be fixed as well, i’m not familiar with its internals.

FYI,
I am using latest foreman 1.22 rc2 and 0.8 version of this plugin.

**Comment by m-bucher** [comment]
This also breaks other Compute-Resources like libvirt.
As far as I see it, this is due to the usage of Deface to introduce the VM-type into the `compute_resource_vms` views.

The best solution in my opinion would be to get rid of defacing the `type`-parameter into the views.
Could this be possible by adding the `type` to the basic compute-resource definition, rather than letting the user decide in the host-create form?

**Comment by tristanrobert** [comment]
A conditional deface on provision compute (compute = proxmox) should be added. PRs are  welcome...
